Fixed Quiz because with search tolowercase it broke
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-MANC pull request #15
Opened 2022-10-07 15:13 UTC by MGliem

2022-10-07 15:15 UTC, Ysedda submitted a review, later dismissed

2022-10-07 15:15 UTC, ngroult approved these changes

2022-10-10 07:13 UTC, YDrogen requested changes

2022-10-10 07:13 UTC, YDrogen commented on src/components/map/Map.jsx
> +                    geo.properties.name.toLowerCase() == searchLower
Jamais 2 sans 3 (`==`)

2022-10-10 07:40 UTC, MGliem commented on src/components/map/Map.jsx
> +                    geo.properties.name.toLowerCase() == searchLower
Ok

2022-10-10 07:56 UTC, Ysedda approved these changes

2022-10-10 08:00 UTC, ngroult approved these changes

2022-10-10 08:04 UTC, YDrogen approved these changes

2022-10-10 08:07 UTC, merged