add country details to search result and color change on click
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-MANC pull request #19
Opened 2022-10-10 13:14 UTC by Ysedda

2022-10-11 07:07 UTC, codelande submitted a review, later dismissed

2022-10-12 09:13 UTC, YDrogen requested changes

2022-10-12 09:13 UTC, YDrogen commented on src/components/map/Map.jsx
> +                    geo.id.includes(clickedCountry) && clickedCountry !== ""
Il manque des parenthèses ici (surtout pour la lisibilité)
Est-ce que c'est : 
`geo.id.includes(clickedCountry) && (clickedCountry !== "")`
ou
`(geo.id.includes(clickedCountry) && clickedCountry) !== ""`
?

2022-10-12 09:23 UTC, Ysedda commented on src/components/map/Map.jsx
> +                    geo.id.includes(clickedCountry) && clickedCountry !== ""
Corrigé

2022-10-12 12:40 UTC, MGliem submitted a review, later dismissed

2022-10-12 12:45 UTC, MGliem approved these changes

2022-10-12 13:32 UTC, ngroult approved these changes

2022-10-12 13:33 UTC, merged