Features/ gamemode choice
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-MANC pull request #25
Opened 2022-10-12 15:05 UTC by codelande

2022-10-13 07:17 UTC, MGliem requested changes

2022-10-13 08:14 UTC, MGliem approved these changes

2022-10-13 11:57 UTC, Ysedda approved these changes

2022-10-13 13:37 UTC, MGliem submitted a review, later dismissed

2022-10-14 08:14 UTC, ngroult submitted a review, later dismissed

2022-10-14 08:20 UTC, YDrogen requested changes

2022-10-14 08:20 UTC, YDrogen commented on src/components/question/Question.jsx
> +    if (setQuestionType) {
`setQuestionType` est toujours `true`

2022-10-14 08:20 UTC, YDrogen commented on src/components/question/Question.jsx
> +        if (mode == true) {
`===` ou changer la condition

2022-10-14 09:05 UTC, MGliem submitted a review, later dismissed

2022-10-14 09:05 UTC, ngroult submitted a review, later dismissed

2022-10-14 09:12 UTC, YDrogen submitted a review, later dismissed

2022-10-14 09:12 UTC, YDrogen commented on src/components/question/Question.jsx
> +  }, [setQuestionType]);
Les dépendances sont pas bonnes Kévin

2022-10-14 09:16 UTC, codelande commented on src/components/question/Question.jsx
> +  }, [setQuestionType]);
?

2022-10-14 09:30 UTC, MGliem submitted a review, later dismissed

2022-10-14 09:31 UTC, ngroult approved these changes

2022-10-14 09:38 UTC, MGliem approved these changes

2022-10-14 09:42 UTC, Ysedda approved these changes

2022-10-14 10:21 UTC, ngroult approved these changes

2022-10-14 10:21 UTC, merged