Contries are colored with red or green after confirming
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-MANC pull request #27
Opened 2022-10-12 23:12 UTC by MGliem

2022-10-13 07:14 UTC, ngroult submitted a review, later dismissed

2022-10-13 07:18 UTC, Ysedda approved these changes

2022-10-13 08:14 UTC, codelande approved these changes

2022-10-13 11:56 UTC, Ysedda submitted a review, later dismissed

2022-10-13 12:17 UTC, YDrogen requested changes

2022-10-13 12:17 UTC, YDrogen commented on src/components/map/Map.jsx
> +                      : geo.id === correctAnswer && isConfirmed
Pourquoi refaire la condition ?

2022-10-13 12:45 UTC, MGliem commented on src/components/map/Map.jsx
> +                      : geo.id === correctAnswer && isConfirmed
1 - Je rentre dans cette "ternaire mess" quand je clique sur un pays
2 - Je n'ai pas encore confirmé, tout le pays se met en vert où j'ai cliqué puisque geo.id !== correctAnswer && isConfirmed est false
3 - je clique sur confirm et ce n'était pas la bonne réponse, le pays où j'ai cliqué se met en rouge mais le pays qui était la bonne réponse se met en vert (2eme condition) Sinon, tout le reste se met en blanc

2022-10-13 15:04 UTC, codelande approved these changes

2022-10-14 07:30 UTC, ngroult approved these changes

2022-10-14 08:03 UTC, YDrogen commented on src/components/map/Map.jsx
> +                      : geo.id === correctAnswer && isConfirmed
My bad, j'avais mal lu la condition

2022-10-14 08:07 UTC, YDrogen approved these changes

2022-10-14 08:12 UTC, merged