Feature/recap game
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-MANC pull request #38
Opened 2022-10-19 14:36 UTC by ngroult

2022-10-19 14:43 UTC, MGliem approved these changes

2022-10-19 14:45 UTC, codelande submitted a review, later dismissed

2022-10-19 14:50 UTC, YDrogen approved these changes

2022-10-19 15:02 UTC, MGliem submitted a review, later dismissed

2022-10-19 15:14 UTC, codelande submitted a review, later dismissed

2022-10-20 08:49 UTC, codelande approved these changes

2022-10-20 10:20 UTC, Ysedda approved these changes

2022-10-20 12:58 UTC, YDrogen approved these changes

2022-10-20 14:19 UTC, codelande approved these changes

2022-10-20 14:21 UTC, MGliem approved these changes

2022-10-20 14:22 UTC, YDrogen requested changes

2022-10-20 14:22 UTC, YDrogen commented on src/pages/Quiz.jsx
> +    if (answer.isCorrect === true) {
`=== true` inutile c:

2022-10-21 07:38 UTC, Ysedda approved these changes

2022-10-21 07:45 UTC, MGliem approved these changes

2022-10-21 07:46 UTC, codelande approved these changes

2022-10-21 07:46 UTC, Ysedda approved these changes

2022-10-21 07:47 UTC, YDrogen approved these changes

2022-10-21 07:49 UTC, merged