Feature accueil
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-MANC pull request #4
Opened 2022-10-05 14:37 UTC by codelande

2022-10-05 14:43 UTC, Ysedda reviewed
map-flou.png -> en anglais s'il te plaît

2022-10-05 15:20 UTC, Ysedda submitted a review, later dismissed

2022-10-06 12:17 UTC, MGliem requested changes

2022-10-06 12:17 UTC, MGliem commented on src/App.jsx
> +  return <div className="absolute-center-container"></div>;
Pourquoi garder cette className si tu le supprime dans le CSS ?

2022-10-06 12:17 UTC, MGliem commented on src/components/home/Home.jsx
> +    <div>
Div qui ne sert pas je crois

2022-10-06 12:21 UTC, MGliem approved these changes

2022-10-06 12:22 UTC, Ysedda submitted a review, later dismissed

2022-10-06 13:04 UTC, Ysedda approved these changes

2022-10-06 13:05 UTC, MGliem approved these changes

2022-10-06 13:45 UTC, YDrogen approved these changes

2022-10-06 14:00 UTC, merged