fix/marker_learn
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-MANC pull request #48
Opened 2022-10-20 14:40 UTC by MGliem

2022-10-20 14:51 UTC, codelande submitted a review, later dismissed

2022-10-20 15:01 UTC, Ysedda approved these changes

2022-10-20 15:18 UTC, YDrogen requested changes

2022-10-20 15:18 UTC, YDrogen commented on src/pages/Learn.jsx
> +        (data) => data.id == clickedCountry
TRIPLE ==================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

2022-10-20 15:20 UTC, MGliem commented on src/pages/Learn.jsx
> +        (data) => data.id == clickedCountry
ZzzZZzzz

2022-10-21 00:27 UTC, Ysedda approved these changes

2022-10-21 07:16 UTC, YDrogen approved these changes

2022-10-21 07:18 UTC, merged