Learn/ details population
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-MANC pull request #63
Opened 2022-10-21 17:10 UTC by Ysedda

2022-10-22 16:18 UTC, MGliem submitted a review, later dismissed

2022-10-24 07:09 UTC, codelande submitted a review, later dismissed

2022-10-24 07:48 UTC, YDrogen requested changes

2022-10-24 07:48 UTC, YDrogen commented on src/components/annotation/Annotation.jsx
> +              Math.round((countryData.population / 1000000) * 10) / 10
Pas opti, le `Math.round` va se réexécuter à chaque render

2022-10-24 14:42 UTC, MGliem approved these changes

2022-10-25 07:10 UTC, codelande approved these changes

2022-10-25 07:24 UTC, YDrogen approved these changes

2022-10-25 09:58 UTC, merged