Feature/zoom on map
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-MANC pull request #64
Opened 2022-10-24 10:17 UTC by MGliem

2022-10-24 14:41 UTC, Ysedda requested changes

2022-10-24 14:41 UTC, Ysedda commented on src/components/map/Map.jsx
> +    console.log(position);
console.log()

2022-10-24 15:04 UTC, Ysedda approved these changes

2022-10-25 07:11 UTC, codelande approved these changes

2022-10-25 09:58 UTC, merged