fix/force_selection_game_mode
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-MANC pull request #77
Opened 2022-10-26 15:21 UTC by MGliem

2022-10-26 15:22 UTC, Ysedda submitted a review, later dismissed

2022-10-26 15:23 UTC, ngroult approved these changes

2022-10-26 15:29 UTC, YDrogen requested changes

2022-10-27 09:22 UTC, codelande approved these changes

2022-10-27 09:54 UTC, Ysedda approved these changes

2022-10-27 10:13 UTC, YDrogen requested changes

2022-10-27 10:13 UTC, YDrogen commented on src/components/rules/Rules.jsx
> +            {!canPlay && (
?

2022-10-27 10:25 UTC, codelande approved these changes

2022-10-27 10:26 UTC, Ysedda approved these changes

2022-10-27 10:29 UTC, merged